projectId: app-ZrjtzHiiAfLu98eezD2upJ
appName: bigmac
description: This a test project
version: "1.0"
hostName: example.test
clusterURL: default
clusterIPs:
- 190.89.89.0
monitoring: true
microservices:
  CartService:
    serviceName: cartservice
    avgReplicas: 1
    minReplicas: 1
    maxReplicas: 1
    dockerImage: eetwt
    containerPort: 8080
  OrderService:
    serviceName: orderservice
    avgReplicas: 2
    minReplicas: 2
    maxReplicas: 2
    dockerImage: werewr
    containerPort: 2121
    serviceEvaluation:
      kubeConfigType:
      - statefulSetBased
  UserService:
    serviceName: userservice
    avgReplicas: 4
    minReplicas: 4
    maxReplicas: 4
    dockerImage: werwerer
    containerPort: 2121
evaluationResult:
  language: Java
  database: MySQL
  microservices:
  - CartService
  - OrderService
  - UserService
